---
    
- name: Apt Dependencies
  ansible.builtin.apt:
    name: "{{ tailscale_dependencies }}"
    update_cache: true
    state: present

- name: Add Tailscale Signing Key
  ansible.builtin.get_url:
    url: "{{ tailscale_apt_key.url }}"
    dest: "{{ tailscale_apt_key.dest }}"
    mode: '0644'
    force: yes

- name: Add Tailscale Repository - Legacy
  ansible.builtin.apt_repository:
    filename: "{{ tailscale_package }}"
    repo: "{{ tailscale_debian_source }}"
    state: present
  when: >
    (ansible_distribution == "Debian" and ansible_distribution_major_version | int <= 12)
    or
    (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int <= 23)

- name: Add Tailscale Repository - Modern
  ansible.builtin.deb822_repository:
    name: "{{ tailscale_package }}"
    types: deb
    uris: "{{ tailscale_deb822_source.uris }}"
    suites: "{{ tailscale_deb822_source.suites }}"
    components: "{{ tailscale_deb822_source.components }}"
    signed_by: "{{ tailscale_apt_key.dest }}"
    enabled: true
  when: >
    (ansible_distribution == "Debian" and ansible_distribution_major_version | int >= 13)
    or
    (ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int >= 24)

- name: Install Tailscale
  ansible.builtin.apt:
    name: "{{ tailscale_package }}"
    state: present
    update_cache: true

- name: Ensure IP Forwarding is Enabled
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/99-tailscale.conf
  loop:
    - { name: net.ipv4.ip_forward, value: '1' }
    - { name: net.ipv6.conf.all.forwarding, value: '1' }

- name: Create systemd unit file for tailscale performance tuning
  ansible.builtin.copy:
    dest: /etc/systemd/system/tailscale-performance-tuning.service
    content: |
      [Unit]
      Description=Tailscale Performance Tuning
      After=network-online.target
      Wants=network-online.target

      [Service]
      Type=oneshot
      ExecStart=/bin/bash -c 'NETDEV=$(ip -o route get 8.8.8.8 | awk "{print \$5}") && ethtool -K $NETDEV rx-udp-gro-forwarding on rx-gro-list off'
      RemainAfterExit=yes

      [Install]
      WantedBy=multi-user.target
    mode: '0644'
    force: yes

- name: Enable tailscale performance tuning service
  ansible.builtin.systemd:
    name: tailscale-performance-tuning.service
    enabled: true
    state: started
    daemon_reload: true